describe('Central de Atendimento ao Cliente TAT', () => {
  beforeEach(() => {
    cy.visit('./src/index.html')
    //Antes de cada teste executar a visita no site.
  })
  it('01-Verifica o titulo da aplicacao', () => {
    cy.title()
      .should('be.equal', 'Central de Atendimento ao Cliente TAT')
    // Should e para verificar verificação imediata//
  })
  it('02-Preencher os campos obrigatorios e enviar o formulario', () => {
    const longtext = Cypress._.repeat('Teste,', 700)
    // Função para repetir um txto por uma contidade de vezes
    cy.get('#firstName')
      .type('Eduardo')
    cy.get('#lastName')
      .type('Manoel')
    cy.get('#email')
      .type('eduardomanoel@yahoo.com.br')
    cy.get('#open-text-area')
      .type(longtext, { delay: 0 })
    //Delay :0 Instantanio
    cy.contains('button', 'Enviar').click()
    cy.get('.success')
      .should('be.visible')
      .contains('Mensagem enviada com sucesso.')
    //# Significa ID. E #significa classe.
  })
  it('03-Exibe mensagem de erro ao submeter o formulario com email com formatacao invalida', () => {
    const longtext = Cypress._.repeat('Teste,', 700)
    // Função para repetir um texto por uma contidade de vezes
    cy.get('#firstName')
      .type('Eduardo')
    cy.get('#lastName')
      .type('Manoel')
    cy.get('#email')
      .type('eduardomanoelyahoo.com.br')
    cy.get('#open-text-area')
      .type(longtext, { delay: 0 })
    //Delay :0 Instantanio
    cy.contains('button', 'Enviar').click()
    cy.get('.error')
      .should('be.visible')
      .contains('Valide os campos obrigatórios!')
  })
  it('04-Validar telefone com campoa numerico', () => {
    cy.get('#firstName')
      .type('Eduardo')
    cy.get('#lastName')
      .type('Manoel')
    cy.get('#email')
      .type('eduardomanoel@yahoo.com.br')
    cy.get('#phone')
      .type('abc')
      .should('have.value', '')
    cy.contains('button', 'Enviar')
      .click()
  })
  it('05-Exibe mensagem de erro quando o telefone se torna obrigatório mas não é preenchido antes do envio do formulário', () => {
    const longtext = Cypress._.repeat('Teste,', 100)
    cy.get('#firstName')
      .type('Eduardo')
    cy.get('#lastName')
      .type('Manoel')
    cy.get('#email')
      .type('eduardomanoel@yahoo.com.br')
    cy.get('#open-text-area')
      .type(longtext, { delay: 0 })
    cy.get('#phone-checkbox')
      .click()
    cy.get('.phone-label-span.required-mark')
      .contains('(obrigatório)')
    cy.contains('button', 'Enviar')
      .click()
    cy.get('.error').should('be.visible')
      .contains('Valide os campos obrigatórios!')
  })
  it('06-Preenche e limpa os campos nome, sobrenome, email e telefone', () => {
    cy.get('#firstName')
      .type('Eduardo')
      .should('have.value', 'Eduardo')
      .clear()
      .should('be.empty')
    cy.get('#lastName')
      .type('Manoel')
      .should('have.value', 'Manoel')
      .clear()
      .should('be.empty')
    cy.get('#email').type('eduardomanoel@yahoo.com.br')
      .should('have.value', 'eduardomanoel@yahoo.com.br')
      .clear()
      .should('be.empty')
    cy.get('#phone-checkbox').click()
    cy.get('.phone-label-span.required-mark').contains('(obrigatório)')
    cy.get('#phone')
      .type('123')
      .should('have.value', '123')
      .clear()
      .should('be.empty')
  })
  it('07-Exibe mensagem de erro ao submeter o formulário sem preencher os campos obrigatórios', () => {
    const longtext = Cypress._.repeat('Teste,', 100)
    cy.get('#firstName')
      .type('Eduardo')
      .should('have.value', 'Eduardo')
      .clear()
      .should('be.empty')
    cy.contains('button', 'Enviar')
      .click()
    cy.get('.error')
      .should('be.visible')
      .contains('Valide os campos obrigatórios!')
    cy.get('#lastName')
      .type('Manoel')
      .should('have.value', 'Manoel')
      .clear()
      .should('be.empty')
    cy.contains('button', 'Enviar').click()
      .click()
    cy.get('.error')
      .should('be.visible')
      .contains('Valide os campos obrigatórios!')
    cy.get('#email').
      type('eduardomanoel@yahoo.com.br')
      .should('have.value', 'eduardomanoel@yahoo.com.br')
      .clear()
      .should('be.empty')
    cy.contains('button', 'Enviar')
      .click()
    cy.get('.error')
      .should('be.visible')
      .contains('Valide os campos obrigatórios!')
    cy.get('#open-text-area')
      .type(longtext, { delay: 0 })
      .should('have.value', longtext)
      .clear()
      .should('be.empty')
    cy.contains('button', 'Enviar')
      .click()
    cy.get('.error')
      .should('be.visible')
      .contains('Valide os campos obrigatórios!')
    cy.get('#phone-checkbox')
      .click()
    cy.get('.phone-label-span.required-mark')
      .contains('(obrigatório)')
    cy.get('#phone')
      .type('123')
      .should('have.value', '123')
      .clear()
      .should('be.empty')
    cy.contains('button', 'Enviar')
      .click()
    cy.wait(50)
    cy.get('.error')
      .should('be.visible')
      .contains('Valide os campos obrigatórios!')
  })
  it('08-Envia o formuário com sucesso usando um comando customizado', () => {
    cy.fillMandatoryFieldsAndSubmit()
    cy.get('.success').should('be.visible')
  })
  it('09-Seleciona um produto (YouTube) por seu texto', () => {
    cy.get('#product')
      .select('YouTube')
      .should('have.value', 'youtube')
      .should('be.visible')
  })
  it('10-Seleciona um produto (Mentoria) por seu valor (value)', () => {
    cy.get('#product')
      .select('mentoria')
      .should('have.value', 'mentoria')
      .should('be.visible')
  })
  it('11-Seleciona um produto (BLog) por seu indice (index)', () => {
    cy.get('#product')
      .select(1)
      .should('have.value', 'blog')
      .should('be.visible')
  })
  it('12-Marcar o tipo de atendimento "Feedback"', () => {
    cy.get('input[type="radio"][value="feedback"]')
      .check()
      .should('be.checked')
  })
  it('13-Marca cada tipo de atendimento 1 resolucao', () => {
    cy.get('input[type="radio"][value="feedback"]')
      .check()
      .should('be.checked')
      .should('have.to.value', 'feedback')
    cy.get('input[type="radio"][value="ajuda"]')
      .check()
      .should('be.checked')
      .should('have.to.value', 'ajuda')
    cy.get('input[type="radio"][value="elogio"]')
      .check()
      .should('be.checked')
      .should('have.to.value', 'elogio')
  })
  it('14-Marca cada tipo de atendimento 2 resolucao', () => {
    cy.get('input[type="radio"]')
      .each(typeOfservice => {
        cy.wrap(typeOfservice)
          .check()
          .should('be.checked')
      })
  })
  it('15-Revisar o exercicio que exibe mensagem de erro ao submeter o formulário sem preencher os campos obrigatórios', () => {
    const longtext = Cypress._.repeat('Teste,', 100)
    cy.get('#firstName')
      .type('Eduardo')
      .should('have.value', 'Eduardo')
      .clear()
      .should('be.empty')
    cy.contains('button', 'Enviar')
      .click()
    cy.get('.error')
      .should('be.visible')
      .contains('Valide os campos obrigatórios!')
    cy.get('#lastName')
      .type('Manoel')
      .should('have.value', 'Manoel')
      .clear()
      .should('be.empty')
    cy.contains('button', 'Enviar').click()
      .click()
    cy.get('.error')
      .should('be.visible')
      .contains('Valide os campos obrigatórios!')
    cy.get('#email').
      type('eduardomanoel@yahoo.com.br')
      .should('have.value', 'eduardomanoel@yahoo.com.br')
      .clear()
      .should('be.empty')
    cy.contains('button', 'Enviar')
      .click()
    cy.get('.error')
      .should('be.visible')
      .contains('Valide os campos obrigatórios!')
    cy.get('#open-text-area')
      .type(longtext, { delay: 0 })
      .should('have.value', longtext)
      .clear()
      .should('be.empty')
    cy.contains('button', 'Enviar')
      .click()
    cy.get('.error')
      .should('be.visible')
      .contains('Valide os campos obrigatórios!')
    cy.get('#phone-checkbox')
      .check() // Alteracao nesta linha para check
    cy.get('.phone-label-span.required-mark')
      .contains('(obrigatório)')
    cy.get('#phone')
      .type('123')
      .should('have.value', '123')
      .clear()
      .should('be.empty')
    cy.contains('button', 'Enviar')
      .click()
    cy.get('.error')
      .should('be.visible')
      .contains('Valide os campos obrigatórios!')
  })
  it('16-Seleciona um arquivo da pasta fixtures', () => {
    cy.get('input[type=file]')
      .selectFile('cypress/fixtures/example.json')
      .should(input => {
        expect(input[0].files[0].name).to.equal('example.json')
      })
  })
  it('17-Seleciona um arquivo simulando um drag-and-drop', () => {
    cy.get('input[type=file]')
      .selectFile('cypress/fixtures/example.json', { action: 'drag-drop' })
      .should(input => {
        expect(input[0].files[0].name).to.equal('example.json')
      })
  })
  it('18-Seleciona um arquivo utilizando uma fixture para a qual foi dada um alias', () => {
    cy.fixture('example.json').as('sampleFile')
    cy.get('input[type=file]')
      .selectFile('@sampleFile')
      .should(input => {
        expect(input[0].files[0].name).to.equal('example.json')
      })
  })
  it('19-Verifica que a política de privacidade abre em outra aba sem a necessidade de um clique', () => {
    cy.contains('a', 'Política de Privacidade')
      .should('have.attr', 'href', 'privacy.html')
      .and('have.attr', 'target', '_blank')
  })
  it('20-Acessa a página da política de privacidade removendo o target e então clicando no link', () => {
    cy.contains('a', 'Política de Privacidade')
      .invoke('removeAttr', 'target')
      .click()
    cy.contains('h1', 'CAC TAT - Política de Privacidade')
      .should('be.visible')
    cy.screenshot()  
  })
})  

