describe('Central de Atendimento ao Cliente TAT', () => {
  beforeEach(() => {
    cy.visit('./src/index.html')
    //Antes de cada teste executar a visita no site.
  })
  it('Verifica o titulo da aplicacao', () => {
    cy.title().should('be.equal', 'Central de Atendimento ao Cliente TAT')
    // Should e para verificar verificação imediata//
  })
  it('Preencher os campos obrigatorios e enviar o formulario', () => {
    const longtext = Cypress._.repeat('Teste,', 700)
    // Função para repetir um txto por uma contidade de vezes
    cy.get('#firstName').type('Eduardo')
    cy.get('#lastName').type('Manoel')
    cy.get('#email').type('eduardomanoel@yahoo.com.br')
    cy.get('#open-text-area').type(longtext, { delay: 0 })
    //Delay :0 Instantanio
    cy.contains('button', 'Enviar').click()
    cy.get('.success').should('be.visible').contains('Mensagem enviada com sucesso.')
    //# Significa ID. E .significa classe.
  })
  it('Exibe mensagem de erro ao submeter o formulario com email com formatacao invalida', () => {
    const longtext = Cypress._.repeat('Teste,', 700)
    // Função para repetir um texto por uma contidade de vezes
    cy.get('#firstName').type('Eduardo')
    cy.get('#lastName').type('Manoel')
    cy.get('#email').type('eduardomanoelyahoo.com.br')
    cy.get('#open-text-area').type(longtext, { delay: 0 })
    //Delay :0 Instantanio
    cy.contains('button','Enviar').click()
    cy.get('.error').should('be.visible').contains('Valide os campos obrigatórios!')
  })
  it('Validar telefone com campoa numerico', () => {
    cy.get('#firstName').type('Eduardo')
    cy.get('#lastName').type('Manoel')
    cy.get('#email').type('eduardomanoel@yahoo.com.br')
    cy.get('#phone')
      .type('abc')
      .should('have.value', '')
    cy.contains('button','Enviar').click()
  })

  it('Exibe mensagem de erro quando o telefone se torna obrigatório mas não é preenchido antes do envio do formulário', () => {
    const longtext = Cypress._.repeat('Teste,', 100)
    cy.get('#firstName').type('Eduardo')
    cy.get('#lastName').type('Manoel')
    cy.get('#email').type('eduardomanoel@yahoo.com.br')
    cy.get('#open-text-area').type(longtext, { delay: 0 })
    cy.get('#phone-checkbox').click()
    cy.get('.phone-label-span.required-mark').contains('(obrigatório)')
    cy.contains('button','Enviar').click()
    cy.get('.error').should('be.visible').contains('Valide os campos obrigatórios!')
  })
  it('Preenche e limpa os campos nome, sobrenome, email e telefone', () => {
    cy.get('#firstName')
      .type('Eduardo')
      .should('have.value', 'Eduardo')
      .clear()
      .should('be.empty')
    cy.get('#lastName')
      .type('Manoel')
      .should('have.value', 'Manoel')
      .clear()
      .should('be.empty')
    cy.get('#email').type('eduardomanoel@yahoo.com.br')
      .should('have.value', 'eduardomanoel@yahoo.com.br')
      .clear()
      .should('be.empty')
    cy.get('#phone-checkbox').click()
    cy.get('.phone-label-span.required-mark').contains('(obrigatório)')
    cy.get('#phone')
      .type('123')
      .should('have.value', '123')
      .clear()
      .should('be.empty')
  })
  it('exibe mensagem de erro ao submeter o formulário sem preencher os campos obrigatórios', () => {
    const longtext = Cypress._.repeat('Teste,', 100)
    cy.get('#firstName')
      .type('Eduardo')
      .should('have.value', 'Eduardo')
      .clear()
      .should('be.empty')
    cy.contains('button', 'Enviar').click()
      .click()
    cy.get('.error')
      .should('be.visible')
      .contains('Valide os campos obrigatórios!')
    cy.get('#lastName')
      .type('Manoel')
      .should('have.value', 'Manoel')
      .clear()
      .should('be.empty')
    cy.contains('button', 'Enviar').click()
      .click()
    cy.get('.error')
      .should('be.visible')
      .contains('Valide os campos obrigatórios!')
    cy.get('#email').type('eduardomanoel@yahoo.com.br')
      .should('have.value', 'eduardomanoel@yahoo.com.br')
      .clear()
      .should('be.empty')
    cy.contains('button', 'Enviar').click()
    cy.get('.error').should('be.visible').contains('Valide os campos obrigatórios!')
    cy.get('#open-text-area')
      .type(longtext, { delay: 0 })
      .should('have.value', longtext)
      .clear()
      .should('be.empty')
    cy.contains('button', 'Enviar').click()
    cy.get('.error').should('be.visible').contains('Valide os campos obrigatórios!')
    cy.get('#phone-checkbox').click()
    cy.get('.phone-label-span.required-mark').contains('(obrigatório)')
    cy.get('#phone')
      .type('123')
      .should('have.value', '123')
      .clear()
      .should('be.empty')
    cy.contains('button', 'Enviar').click()
    cy.get('.error').should('be.visible').contains('Valide os campos obrigatórios!')
  })
  it('Envia o formuário com sucesso usando um comando customizado', () => {
    cy.fillMandatoryFieldsAndSubmit()
    cy.get('.success').should('be.visible')
  })
  it('', () => {

  })
})
